name: Deprecated (use root .github/workflows/deploy.yml)

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is deprecated. Use the root workflow at .github/workflows/deploy.yml"
